---
baseURL: http://0x1.im
disablePathToLower: true
languageCode: zh-hans
title: Scholer's Homapage
pygmentsCodefences: true
pygmentsUseClasses: true
publishDir: docs
theme: hello-friend-ng

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  social:
    - name: github
      url: 'https://github.com/'

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 10
    - name: About
      url: /about/
      weight: 20
